before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./jenv.go
    ldflags:
      - -s -w
      - -X github.com/WhyWhatHow/jenv/cmd.Version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'



changelog:
  enabled: true
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: "^feat:"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^fix:"
      order: 1
  template: "templates/changelog.md.tpl"

release:
  github:
    owner: "whywhathow"
    name: "jenv"
    header: "templates/header.md"